// LOCALHOST

### Get all academicDetails
GET http://localhost:10000/academicDetails

### Get all  classInfo
GET http://localhost:10000/classInfo

### Get all finances 
GET http://localhost:1000/finances

### Get all students
GET http://localhost:10000/students

### Get academicDetails by id 
GET http://localhost:3000/academicDetails/67adeafa2a5892d7649e6508

### Get classInfo by id 
GET http://localhost:3000/classInfo/67adee7a2a5892d7649e650b

### Get finances by id 
GET http://localhost:3000/finances/67af3f050d88e45645a28497

### Get students by id
GET http://localhost:3000/students/67af43090d88e45645a2849b

### Create academicDetails
POST http://localhost:3000/academicDetails HTTP/1.1

{
"major": "Photography", 
"minor": "Knitting",
 "faculty":"Arts", 
 "gpa": 2.5, 
 "enrollmentStatus": "Registered", 
 "admissionDate": 2025-01-01
 
}

### Create classInfo
POST http://localhost:3000/classInfo HTTP/1.1

{
"currentCourses" : "Photography101, Art and Culture, History of Art", 
"completedCourses": "0", 
"creditsEarned": "0", 
"academicStanding": "Enrolled"
} 

###Create finances 
POST http://localhost:3000/finances HTTP/1.1
{
  "tuitionBalance":30000,
  "scholarships":"none",
  "paymentStatus":"Paid"
  
}

###Create students
POSt http://localhost:3000/students HTTP/1.1
{
  "firstName":"Sammy",
  "lastName":"Steward",
  "dateOfBirth":1992-06-08,
  "gender":"Female",
  "physicalAddress":"56 Gong Street Centurion",
  "phone":"079 378 2390",
  "email":"sammys@yourmail.com"
}
### PUT academicdetails
PUT http://localhost:3000/orders/ HTTP/1.1

{
  "major": "Photography", 
"minor": "History",
 "faculty":"Arts", 
 "gpa": 2.5, 
 "enrollmentStatus": "Registered", 
 "admissionDate": 2025-01-01

}

### PUT classInfo
PUT http://localhost:3000/classInfo HTTP/1.1

{
"currentCourses" : "Photography101, Art and Culture, History of Art", 
"completedCourses": "0", 
"creditsEarned": "0", 
"academicStanding": "Registered"
}

### PUT finances
PUT http://localhost:3000/finances HTTP/1.1
{
  "tuitionBalance":30000,
  "scholarships":"SchoolAid",
  "paymentStatus":"Paid"
  

}

##PUT students
PUT http://localhost:3000/students HTTP/1.1
{
  "firstName":"Samantha",
  "lastName":"Steward",
  "dateOfBirth":1992-06-08,
  "gender":"Female",
  "physicalAddress":"56 Gong Street Centurion",
  "phone":"079 378 2390",
  "email":"sammys@yourmail.com"
}

### Delete order 
DELETE http://localhost:3000/orders/67a12c7ccb15b7715e403f88 HTTP/1.1

### Delete product 
DELETE http://localhost:3000/products/67a0ca9a45afc7af170b0d65 HTTP/1.1